name: ssec-project
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.11,<3.12
  - ipykernel
  - ipywidgets
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - numpy
  - pandas
  - matplotlib
  - pydantic
  - conda-lock
  - pip