name: ssec-scipy2024
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupyter-panel-proxy
  - langchain>=0.1.20
  - libopenblas
  - tqdm
  - fsspec
  - gcsfs
  - s3fs
  - pandas
  - streamlit
  - panel
  - pip
  - pip:
    - qdrant-client
    - sentence-transformers
    - llama-cpp-python>=0.2.70 -C cmake.args="-DLLAMA_BLAS=ON;-DLLAMA_BLAS_VENDOR=OpenBLAS"
    - rse-toolbox[olmo] @ git+https://github.com/uw-ssec/rse-toolbox.git
  
